config/routes.rb
CF::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "(:locale)", :locale => /en|ba|hi/ do

    root 'campaigns#index'

    resources :categories

    resources :transactions

    resources :campaigns

    devise_for :users

    get '/donate/:campaign_id', to: 'transactions#new', as: :donate
    get '/dashboard', to: 'users#show', as: :dashboard
    post '/verify/:tran_id', to: 'transactions#verify', as: :verify_transaction
    post '/regenerate_otp/:tran_id', to: 'transactions#generate_otp_code', as: :otp_regenerate
    get '/:category_id/campaigns', to: 'campaigns#index', as: :category_campaign
    get '/users/:action(/:id)', :controller => 'users'
    get 'tags/:tag', to: 'campaigns#index', as: :tag
    post '/store_bank_account', to: 'balanced#store_bank_account', as: :store_bank_account
    post '/store_credit_card', to: 'balanced#store_credit_card', as: :store_credit_card
    get '/credit_card_form', to: 'transactions#credit_card_form'
    get '/statistics', to: 'categories#index', as: :statistics

    get '/about_us', to: 'users#about', as: :about_us
    get '/contact_us', to: 'users#contact', as: :contact_us
end

  post '/vote_for_campaign/:id', to: 'campaigns#vote_for_campaign', as: :campaign_vote

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :user #association User.first.campaigns, campaign.user
  belongs_to :category

  has_many :transactions
  acts_as_voteable

  acts_as_taggable # Alias for acts_as_taggable_on :tags

  has_attached_file :banner #papeclip
  has_attached_file :video #papeclip

  validates :title, presence: true
  validates :info, presence: true
  validates :days, presence: true
  validates :target, presence: true
  validates :days, numericality: { only_integer: true }
  validates :target, numericality: true

  validates_attachment :banner, presence: true,
    content_type: { :content_type => ["image/jpg", 'image/png', 'image/jpeg'] },
    size: { :in => 0..400.kilobytes }

  validates_attachment :video, presence: true,
    content_type: { :content_type => "video/mp4" },
    size: { :in => 0..10000.kilobytes }

  # searchable do
  #   text :name, :info
  # end

  def add_details(bank_uri)
    merchant_uri    = self.user.find_or_create_customer_uri
    merchant        = Balanced::Customer.fetch(merchant_uri)

    bank            = Balanced::BankAccount.fetch(bank_uri)
    self.bank_uri   = bank_uri

    bank.associate_to_customer(merchant)

    order           = merchant.create_order(description: "#{self.id} : #{self.title}")
    self.order_uri  = order.href
    self.save
  end

  def fullfill_payment(closed_date = Date.today) #take todays date if no parameter passed
    #ideally we should update before money is transferring so that new payment is not done meanwhile
    self.reload.update_attributes(closed_date: closed_date, closed_reason: 'success')

    order         = Balanced::Order.fetch self.order_uri
    bank_account  = Balanced::BankAccount.fetch self.bank_uri

    order.credit_to(
      destination: bank_account,
      amount: self.collected * 100 * 0.95 #transfer 95% money
      # amount: order.amount_escrowed * 0.95
    )
  end

  def refund_payment(closed_date)
    self.reload.update_attributes(closed_date: closed_date, closed_reason: 'expired')
    order         = Balanced::Order.fetch self.order_uri
    order.debits.each do |debit|
      debit.refund
    end
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :vote_for_campaign]

  # GET /campaigns
  def index
    @campaigns = @q.result(distinct: true)

    if params[:tag]
      @campaigns = Campaign.where(approved: true, closed_date: nil).tagged_with(params[:tag])
    elsif params[:category_id]
      @campaigns = Campaign.all.where(category_id: params[:category_id], approved: true, closed_date: nil)
    end

    @root = true if params[:q].nil? && params[:tag].nil? && params[:category_id].nil?

  end

  # GET /campaigns/1
  def show
      @first_user = @campaign.transactions.each.first.try(:user).try(:name)
      #PUT TRY
      @highest_amount =  @campaign.transactions.map{|t| t.amount}.max
      @highest_user =  @campaign.transactions.map{|t| [t.amount,t.user.name]}.max.try(:last)
  end

  def vote_for_campaign

    @campaign = Campaign.find(params[:id])
    current_user.vote_exclusively_for(@campaign)
    render text: @campaign.votes.count
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
    all_tags = ActsAsTaggableOn::Tagging.includes(:tag).where(taggable_type: 'Campaign').map(&:tag)
    @comma_tags_string = all_tags.map{|t| "'#{t.name}'" }.join(',')
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user_id = current_user.id

    if verify_recaptcha(@campaign) && params[:balancedBankAccountURI].present? && @campaign.save!
      @campaign.add_details(params[:balancedBankAccountURI])

      CampaignMailer.welcome_email(@campaign.user, @campaign).deliver
      # redirect_to campaign_path(I18n.locale, @campaign.id), notice: 'Campaign was successfully created.'
      redirect_to root_path, notice: 'Your campaign has been created successfully. It will be published once approved by admin.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /campaigns/1
  def update
    if @campaign.update(campaign_params)
      redirect_to campaign_path(I18n.locale, @campaign.id), notice: 'Campaign was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /campaigns/1
  def destroy
    @campaign.destroy
    redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def campaign_params
      params.require(:campaign).permit(:title, :info, :days, :target, :user_id, :banner, :video, :category_id, :socialplug, :tag_list, :Thumbs_up, :first_reward, :highest_reward) if params[:campaign]
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_campaign_item.html.slim
.item
  / a.image href="/campaigns/#{campaign.id}"

  = link_to(campaign_path(I18n.locale, campaign.id), class: 'image') do
    img src=(campaign.banner.url)
  .content
    .name
      = campaign.title
    p.description
      | by&nbsp;
      span.orange.text
      = campaign.user.name
      br
      | on&nbsp;
      = date_display(campaign.created_at)
      br
      = campaign.info.split(' ').slice(0, 15).join(' ')
      | &#133;

      br
      - percent = (campaign.collected*100.0/campaign.target).round(2)
      .ui.successful.thin.progress
        .bar style="width:#{percent > 100 ? 100 : percent}%;"

      br

      .ui.celled.grid
        .row
          .column style=""
            p
              = t 'campaigns.item.funded'
              br
              = percent
              | %
          .column style=""
            p
              = t 'campaigns.item.target'
              br
              = campaign.target
        .row
          .column
            p style='text-align: center'
              = distance_of_time_in_words_to_now(campaign.created_at + campaign.days.days)
              | &nbsp;
              = t 'campaigns.item.togo'

app/views/campaigns/_form.html.slim
script src="https://js.balancedpayments.com/v1/balanced.js" type="text/javascript"

.ui.segment.basic.paged.stacked
  = form_for @campaign, html: { multipart: true } do |f|
    .ui.message
      .header
        = t 'campaigns.form.newC'

    - if @campaign.errors.any?
      .ui.error.message
        .header
          = pluralize(@campaign.errors.count, "error")
          | &nbsp;
          = t 'campaigns.form.prohibitCamp'
        ul.ui.list
          - @campaign.errors.full_messages.each do |msg|
            li= msg

    .ui.small.steps style='width:100%'
      .ui.step.active  style='width:33%'
        i.white.info.letter.icon
        = t 'campaigns.form.campinfo'
        i.green.checkmark.circular.inverted.icon
      .ui.step  style='width:33%'
        i.white.photo.icon
        = t 'campaigns.form.campAsset'
        i.green.checkmark.circular.inverted.icon
      .ui.step  style='width:33%'
        i.white.payment.icon
        = t 'campaigns.form.bankDetail'
        i.green.checkmark.circular.inverted.icon

    .ui.form.segment
      .form-step
        .ui.small.ribbon.teal.label
          = t 'campaigns.form.mate'
        br
        br
        .field
          label
            = t 'campaigns.form.title'
          .ui.labeled.icon.input
            = f.text_field :title
        .field
          label
            = t 'campaigns.form.information'
          .ui.labeled.icon.input
            = f.text_field :info
        .field
          label
            = t 'campaigns.form.Days'
          .ui.labeled.icon.input
            = f.number_field :days
        .field
          label
            = t 'campaigns.form.monetaryTarget'
          .ui.labeled.icon.input
            = f.number_field :target
        .field
          label
            = t 'campaigns.form.freward'
          .ui.labeled.icon.input
            = f.text_field :first_reward
        .field
          label
            = t 'campaigns.form.hreward'
          .ui.labeled.icon.input
            = f.text_field :highest_reward


        .ui.tiny.teal.right.labeled.icon.button.floated.next_button
          i.right.arrow.icon
          = t 'campaigns.form.next'

      .form-step.hide
        .ui.small.ribbon.teal.label
          = t 'campaigns.form.selfie'
          | &nbsp;
          i.icon.smile.white.large
        br
        br
        .field
          label
            = t 'campaigns.form.campBanner'
          .ui.labeled.icon.input
            = f.file_field :banner
        .field
          label
            = t 'campaigns.form.campVideo'
          .ui.labeled.icon.input
            = f.file_field :video
        .field
          - taglabel = t 'campaigns.form.tag1'
          = f.label :tag_list, taglabel
          br
          .ui.labeled.icon.input
            = f.text_field :tag_list, class: 'tags_input'
        .field
          .ui.labeled.icon.input
            = t 'campaigns.form.selCampCat'
            | #{f.collection_select :category_id, Category.all.order(:name),:id,:name}
        .field
          label
            = t 'campaigns.form.social'
          .ui.labeled.icon.input
            = f.text_field :socialplug

        .ui.tiny.teal.right.labeled.icon.button.floated.next_button
          i.right.arrow.icon
          = t 'campaigns.form.next'
        .ui.tiny.teal.left.labeled.icon.button.floated.prev_button
          = t 'campaigns.form.prev'
          i.left.arrow.icon

      .form-step.hide
        .ui.small.ribbon.teal.label
          i.icon.money.white.large
          = t 'campaigns.form.dreams'
          | &nbsp;
          i.icon.money.white.large
        br
        br
        .field
          = label_tag "ba-name", "#{t 'campaigns.form.accName'}"
          .ui.labeled.icon.input
            = text_field_tag "ba-name", nil, :placeholder => "Account Holder's Name", :class => "ba-name", :autocomplete => "off"
        .field
          = label_tag "ba-rn", "#{t 'campaigns.form.accRouNo'}"
          .ui.labeled.icon.input
            = text_field_tag "ba-rn", nil, :placeholder => "Routing Number", :class => "ba-rn", :autocomplete => "off"
        .field
          = label_tag "ba-an", "#{t 'campaigns.form.accNo'}"
          .ui.labeled.icon.input
            = text_field_tag "ba-an", nil, :placeholder => "Account Number", :class => "ba-an", :autocomplete => "off"
        .field
          = label_tag "ba-type", "#{t 'campaigns.form.accType'}"
          .ui.labeled.icon.input
            = select_tag "ba-type", "<option value='' disabled selected style='display:none;'>Select Account Type</option><option value=\"checking\">CHECKING</option><option value=\"savings\">SAVINGS</option>".html_safe

        div
          = recaptcha_tags

        = f.submit "#{t 'campaigns.form.create'}", class: 'ui teal submit button right floated'
        .ui.tiny.teal.left.labeled.icon.button.floated.prev_button
          = t 'campaigns.form.prev'
          i.left.arrow.icon

      / need to write js here.. coz we need to pass tags to selct 2 .. so pure js nai hai.. rails code bhi hai
      / pure rails cannot me executed in .js file
    javascript:
      $(function(){
        $('.tags_input').select2({tags:[ #{@comma_tags_string.try(:html_safe)} ]})
      });

app/views/campaigns/index.html.slim
script src="//unslider.com/unslider.min.js" type="text/javascript"

.ui.basic.segment.no_radius.paged style='width:1140px !important;'
  - if params[:category_id].present?
    .ui.basic.stackable.items.segment.no_radius.paged
      .ui.header
        = Category.find(params[:category_id]).name
      - @campaigns.each do |campaign|
        = render partial: 'campaign_item', locals: { campaign: campaign }

  - elsif params[:tag].present?
    .ui.basic.stackable.items.segment.no_radius.paged
      .tag style='font-size: 14px; cursor: default; color: black;'
        = params[:tag].try(:humanize)

      .ui.clearing.divider

      - @campaigns.each do |campaign|
        = render partial: 'campaign_item', locals: { campaign: campaign }

  - elsif params[:q].present?
    .ui.basic.stackable.items.segment.no_radius.paged
      .ui.header
        | Your search result for "
        em = params[:q][:title_cont]
        |"
      .ui.clearing.divider
      - @campaigns.each do |campaign|
        = render partial: 'campaign_item', locals: { campaign: campaign }

  - else
    .ui.two.column.grid
      .column
        .ui.segment.stackable.items.inline-block
          .ui.ribbon.label.purple
            = t 'campaigns.index.popular'
          .ui.invisible.clearing.divider

          - Campaign.first(2).each do |campaign|
            = render partial: 'campaign_item', locals: { campaign: campaign }

      .ui.vertical.divider
        i.heart.icon.red

      .column
        .ui.segment.stackable.items.inline-block.left_margin
          .ui.ribbon.label.teal
            = t 'campaigns.index.newlyLaun'
          .ui.invisible.clearing.divider

          - Campaign.last(2).each do |campaign|
            = render partial: 'campaign_item', locals: { campaign: campaign }


    .ui.clearing.invisible.divider
  / = stylesheet_link_tag 'jquery.rambling.slider'
  / = javascript_include_tag 'jquery.rambling.slider.min.js'

app/views/campaigns/new.html.slim
= render 'form'
/ = link_to 'Back', campaigns_path

app/views/campaigns/show.html.slim
- content_for :title do
  = @campaign.title
.ui.basic.segment.no_radius.paged.campaign_show style='width:1140px !important; overflow:hidden; margin-bottom: 50px; !important'
  - if (@campaign.id > Campaign.last.id - 2)
    a.ui.right.teal.corner.label
      .text
       = t 'campaigns.show.new'

  img.circular.ui.image src=(@campaign.banner.url)

  h1.title
    = @campaign.title

  h2.pinline
    span
      = t 'campaigns.show.campTag'

  p.campaign_info
    = @campaign.info

  .ui.celled.grid
    / = link_to "like", vote_for_campaign_path(@campaign)
    /= Vote(vote).count
    /= Campaign.group("category").count
    .row
      .column.two
        video controls="" height="470" width="650"
          source src=@campaign.video.url type=@campaign.video.content_type
      .column
        .row
          p
          .ui.celled.grid
              .row
                .column style=""
                  p
                    = t 'campaigns.show.funded2'
                    - percent = (@campaign.collected*100.0/@campaign.target).round(2)
                    br
                    = percent
                    | %
                .column style=""
                  p
                    = t 'campaigns.show.target2'
                    br
                    = @campaign.target
              .row
                .column

                  .ui.successful.thin.progress
                    .bar style="width:#{percent > 100 ? 100 : percent}%;"
                  p style='text-align: center'
                    = distance_of_time_in_words_to_now(@campaign.created_at + @campaign.days.days)
                    | &nbsp;
                    = t 'campaigns.show.togo2'

          .ui.divided.relaxed.list

            - if current_user.try(:id) != @campaign.user_id
              .item style='text-align: center;'
                = link_to(donate_path(I18n.locale, @campaign.id)) do
                  .ui.animated.fade.button.green
                    .visible.content
                      = t 'campaigns.show.contriNow'
                    .hidden.content
                      = t 'campaigns.show.gofoi'

            .item style='text-align: center;'
              - if user_signed_in? && !current_user.voted_on?(@campaign)
                .flipper-container href="#voteup" vote_path=campaign_vote_path(@campaign.id)
                  #voteup.flipper
                    .front-face data-icon="★" href="#"
                      span data-hover="Clicked"
                        = t 'campaigns.show.vote'
                    .back-face data-icon="♥"
                      = t 'campaigns.show.thanku'

              span.vote_counter_box style='color: #333;'
                span.vote_counter
                  = @campaign.votes.count
                |&nbsp;
                i.heart.icon.vote_icon
                span.hide
                  | votes


            h5.item
              = t 'campaigns.show.freward2'
              em
                | &nbsp;
                = @campaign.first_reward
              br
              = t 'campaigns.show.given'
              em
                | &nbsp;
                = @first_user


            h5.item
              = t 'campaigns.show.hreward2'
              em
                = @campaign.highest_reward
              br
              = t 'campaigns.show.given'
              em
                = @highest_user
              br
              = t 'campaigns.show.amountDon'
              em
                = @highest_amount


            .item
              - @campaign.tag_list.each do |tag|
                = link_to tag, tag_path(I18n.locale, tag), class: 'ui small purple label camplabel'