config/routes.rb
CF::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "(:locale)", :locale => /en|ba|hi/ do

    root 'campaigns#index'

    resources :categories

    resources :transactions

    resources :campaigns

    devise_for :users

    get '/donate/:campaign_id', to: 'transactions#new', as: :donate
    get '/dashboard', to: 'users#show', as: :dashboard
    post '/verify/:tran_id', to: 'transactions#verify', as: :verify_transaction
    post '/regenerate_otp/:tran_id', to: 'transactions#generate_otp_code', as: :otp_regenerate
    get '/:category_id/campaigns', to: 'campaigns#index', as: :category_campaign
    get '/users/:action(/:id)', :controller => 'users'
    get 'tags/:tag', to: 'campaigns#index', as: :tag
    post '/store_bank_account', to: 'balanced#store_bank_account', as: :store_bank_account
    post '/store_credit_card', to: 'balanced#store_credit_card', as: :store_credit_card
    get '/credit_card_form', to: 'transactions#credit_card_form'
    get '/statistics', to: 'categories#index', as: :statistics

    get '/about_us', to: 'users#about', as: :about_us
    get '/contact_us', to: 'users#contact', as: :contact_us
end

  post '/vote_for_campaign/:id', to: 'campaigns#vote_for_campaign', as: :campaign_vote

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :index]
  #wepay = WePay.new(client_id, client_secret, use_stage, true, api_version)

  def verify
    @transaction = Transaction.find(params[:tran_id])
    is_verified = @transaction.authenticate_otp(params[:code], drift: 90)
    if is_verified
      @transaction.mark_verifed_and_debit
    else
      flash[:notice] = 'InValid Code'
    end
    redirect_to transaction_path(I18n.locale, @transaction.id)
  end

  def generate_otp_code
    @transaction = Transaction.find(params[:tran_id])
    @campaign  = @transaction.campaign
    number_to_send_to = '+919930443487'
    send_otp_code(number_to_send_to)
    flash[:notice] = "Sent new OTP code to ur Mobile"
    redirect_to transaction_path(I18n.locale, @transaction.id)
  end

  # GET /transactions
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  def show
      @campaign = @transaction.campaign
      @related_campaign =  @campaign.category.campaigns.where("id != ?", @campaign.id).limit(2)
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @transaction.campaign_id = params[:campaign_id]
  end

def credit_card_form
end

  # GET /transactions/1/edit
  # def edit
  # end

  # POST /transactions
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id

    @transaction.card_uri = params[:balancedCreditCardURI]

    if @transaction.save
      @campaign  = @transaction.campaign
      number_to_send_to = '+919930443487'
      send_otp_code(number_to_send_to)
      redirect_to transaction_path(I18n.locale, @transaction.id)
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /transactions/1
  # def update
  #   if @transaction.update(transaction_params)
  #     redirect_to @transaction, notice: 'Transaction was successfully updated.'
  #   else
  #     render action: 'edit'
  #   end
  # end

  # # DELETE /transactions/1
  # def destroy
  #   @transaction.destroy
  #   redirect_to transactions_url, notice: 'Transaction was successfully destroyed.'
  # end

  private
    def send_otp_code(number_to_send_to)
      client = Twilio::REST::Client.new(TWILIO_CONFIG['sid'], TWILIO_CONFIG['token'])

      # Create and send an SMS message

      client.account.sms.messages.create(
        from: TWILIO_CONFIG['from'],
        to: number_to_send_to,

        body: "OTP code for #{@campaign.title.slice(0,15)} is #{@transaction.otp_code} with amount #{@transaction.amount}"
      )
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def transaction_params
      params.require(:transaction).permit(:amount, :user_id, :campaign_id)
    end


end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_credit_card_form.html.slim
= form_tag "/store_credit_card", :method => :post, :id => "credit-card-form", :class => "form-horizontal" do
  .control-group
    = label_tag "cc-number", "Card Number", :class => "control-label"
    .controls
      = text_field_tag "cc-number", nil, :placeholder => "Enter Credit Card Number", :class => "cc-number", :autocomplete => "off"
  .control-group
    = label_tag "cc-em", "Expiration", :class => "control-label"
    .controls
      = text_field_tag "cc-em", nil, :placeholder => "Expiration Month", :class => "cc-em", :autocomplete => "off"
      = text_field_tag "cc-em", nil, :placeholder => "Expiration Year", :class => "cc-ey", :autocomplete => "off"
  .control-group
    = label_tag "cc-csc", "Security Code", :class => "control-label"
    .controls
      = text_field_tag "cc-csc", nil, :placeholder => "Security Code", :class => "cc-csc", :autocomplete => "off"
  .control-group
    .controls
      = submit_tag "Submit", :class => "btn btn-primary btn-large"

app/views/transactions/_form.html.slim
= form_for(@transaction) do |f|
  - if @transaction.errors.any?
    #error_explanation
      h2
        = pluralize(@transaction.errors.count, "error")
        = t 'transactions.form.prohibitTrans'
      ul
        - @transaction.errors.full_messages.each do |msg|
          li= msg
  .ui.form.segment
    .field
      label
        = t 'transactions.form.amountTrans'
      .ui.labeled.icon.input
        = f.text_field :amount
    .field
      = f.hidden_field :user_id
    .field
      = f.hidden_field :campaign_id
    .actions
      = f.submit
        = t 'transactions.form.submit', class: 'ui blue submit button'

app/views/transactions/credit_card_form.html.slim
script src="https://js.balancedpayments.com/v1/balanced.js" type="text/javascript"

= form_tag "/store_credit_card", :method => :post, :id => "credit-card-form", :class => "form-horizontal" do
  .control-group
    = label_tag "cc-number", "Card Number", :class => "control-label"
    .controls
      = text_field_tag "cc-number", nil, :placeholder => "Enter Credit Card Number", :class => "cc-number", :autocomplete => "off"
  .control-group
    = label_tag "cc-em", "Expiration", :class => "control-label"
    .controls
      = text_field_tag "cc-em", nil, :placeholder => "Expiration Month", :class => "cc-em", :autocomplete => "off"
      = text_field_tag "cc-em", nil, :placeholder => "Expiration Year", :class => "cc-ey", :autocomplete => "off"
  .control-group
    = label_tag "cc-csc", "Security Code", :class => "control-label"
    .controls
      = text_field_tag "cc-csc", nil, :placeholder => "Security Code", :class => "cc-csc", :autocomplete => "off"
  .control-group
    .controls
      = submit_tag "Submit", :class => "btn btn-primary btn-large"

app/views/transactions/new.html.slim
script src="https://js.balancedpayments.com/v1/balanced.js" type="text/javascript"
script src="/js/jquery.creditCardValidator.js" type="text/javascript"

= form_for( @transaction, html: { id: 'credit-card-form', class: ' ui form transaction_form overflow_check' } ) do |f|
  h2
    = t 'transactions.new.newTransaction'

  - if @transaction.errors.any?
    .ui.error.message
      .header
        = pluralize(@transaction.errors.count, "error")
        = t 'transactions.new.prohibitTrans2'
      ul.ui.list
        - @transaction.errors.full_messages.each do |msg|
          li = msg

  .ui.error.message.ui_errors
    .header
      | Errors
    ul.ui.list

  ul
    li
      ul.cards
        li.visa Visa
        li.visa_electron Visa Electron
        li.mastercard MasterCard
        li.maestro Maestro
        li.amex Amex
    br

    li
      label for="card_number"
        = t 'transactions.new.creditcardNo'
        = text_field_tag "cc-number", nil, :placeholder => "Enter Credit Card Number", :class => "cc-number", :autocomplete => "off", id: 'card_number'

    li.vertical
      / ul
      li
        label.small.width for="expiry_month"
          = t 'transactions.new.expiryMonth'
          small
            | &nbsp; mm

          = text_field_tag "cc-em", nil, :placeholder => "Expiration Month", :class => "cc-em", :autocomplete => "off", id: 'expiry_month', maxlength: 5

        label.small.width for="expiry_year"
          = t 'transactions.new.expiryMonth'
          small
            | &nbsp; yyyy

          = text_field_tag "cc-ey", nil, :placeholder => "Expiration Year", :class => "cc-ey", :autocomplete => "off", id: 'expiry_year', maxlength: 5
    li
      label for="cvv"
        = t 'transactions.new.securityCode'
        = text_field_tag "cc-csc", nil, :placeholder => "Security Code", :class => "cc-csc", :autocomplete => "off", id: 'cvv', maxlength: "4"

    li
      label for="amount"
        = t 'transactions.new.amountTrans2'
        = f.number_field :amount, :placeholder => "Amount Pledged", id: 'amount'

    li
      br
      = f.hidden_field :user_id
      = f.hidden_field :campaign_id
      = f.submit "#{t 'transactions.new.submit'}" , class: 'ui teal submit button right floated'

app/views/transactions/show.html.slim
.ui.basic.segment.no_radius.paged style='width:1140px !important;'
  table.ui.celled.table.segment
    thead
      tr
        th
          = t 'transactions.show.trans'
        th
        /th
          /= t 'transactions.show.suggestion'
    tbody
      tr
        td
          - if @transaction.verified
            p
              = t 'transactions.show.thanksTrans'
          - else
            p
              = t 'transactions.show.verifyTrans'
          table.ui.fluid.table
            tr
              td
                strong
                  = t 'transactions.show.campaignTrans'
              td
                = @transaction.campaign.title
            tr
              td
                strong
                  = t 'transactions.show.amountTrans'
              td
                = @transaction.amount

        td
          - if !@transaction.verified
            = form_tag(verify_transaction_path(I18n.locale, @transaction.id), method: :post, style:'width: 300px; float: left; margin-left: 170px;') do
              .ui.form.segment
                .field
                  .ui.labeled.icon.input
                    = t 'transactions.show.otpEnter'
                    = number_field_tag 'code'

                    = submit_tag 'Save' , class: 'ui blue submit button'
            = link_to 'Regenerate OTP code', otp_regenerate_path(I18n.locale, @transaction), method: :post, style: 'margin: 55px 35px; float: left;'
      tr
        td colspan=2
      tr
        th colspan=2
          = t 'transactions.show.suggestion'
      tr
        td colspan=2
          .ui.basic.stackable.items.segment.no_radius.paged
            .ui.header
            - if @related_campaign.count.zero?
              h3 style='margin:10px 300px;'
                | No Similar Campaign Found!
            - else
              - @related_campaign.each do |campaign|
                = render partial: 'campaigns/campaign_item', locals: { campaign: campaign }