config/routes.rb
CF::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "(:locale)", :locale => /en|ba|hi/ do

    root 'campaigns#index'

    resources :categories

    resources :transactions

    resources :campaigns

    devise_for :users

    get '/donate/:campaign_id', to: 'transactions#new', as: :donate
    get '/dashboard', to: 'users#show', as: :dashboard
    post '/verify/:tran_id', to: 'transactions#verify', as: :verify_transaction
    post '/regenerate_otp/:tran_id', to: 'transactions#generate_otp_code', as: :otp_regenerate
    get '/:category_id/campaigns', to: 'campaigns#index', as: :category_campaign
    get '/users/:action(/:id)', :controller => 'users'
    get 'tags/:tag', to: 'campaigns#index', as: :tag
    post '/store_bank_account', to: 'balanced#store_bank_account', as: :store_bank_account
    post '/store_credit_card', to: 'balanced#store_credit_card', as: :store_credit_card
    get '/credit_card_form', to: 'transactions#credit_card_form'
    get '/statistics', to: 'categories#index', as: :statistics

    get '/about_us', to: 'users#about', as: :about_us
    get '/contact_us', to: 'users#contact', as: :contact_us
end

  post '/vote_for_campaign/:id', to: 'campaigns#vote_for_campaign', as: :campaign_vote

end

app/views/layouts/_footer.html.slim
footer
  .big-image style=("background-image: url(http://tympanus.net/Tutorials/MediumStylePageTransition/images/5.jpg);")
    .inner
      .fader
        .text
          h1.title
            = t 'slayout.sfooter.bb'
          h2.description
            i
              = t 'slayout.sfooter.bbtag'

          = link_to "English", url_for(locale: :en)
          | &nbsp; &nbsp;
          = link_to "Hindi", url_for(locale: :hi)
          | &nbsp; &nbsp;
          = link_to "Bengali", url_for(locale: :ba)
          | &nbsp; &nbsp;
          br
          br
          = link_to "About Us", about_us_path
          | &nbsp; &nbsp;

          = link_to "Contact Us", contact_us_path()
          | &nbsp; &nbsp;


        .segment.social
          ul.tt-wrapper
            li
              a.tt-gplus href="#"
                span
                  = t 'slayout.sfooter.social1'
            li
              a.tt-twitter href="#"
                span
                  = t 'slayout.sfooter.social2'
            li
              a.tt-facebook href="#"
                span
                  = t 'slayout.sfooter.social4'
            li
              a.tt-linkedin href="#"
                span
                  = t 'slayout.sfooter.social5'

          / .ui.clearing.invisible.divider

app/views/layouts/_header.html.slim
.header_nav.no_top_margin
  nav.ui.text.menu
    a.item href='/' class=(category_active_class('all'))
      i.bitcoin.large.white.icon
      = t 'slayout.sheader.home'

    .ui.dropdown.item class="#{category_active_class('category')}"
      = t 'slayout.sheader.CamCat'
      i.dropdown.icon
      .menu.category
        - for category in @categories
          = link_to category_campaign_path(I18n.locale, category.id), method: :get, class: "item #{category_active_class(category.id)}"
            = category.name
    = link_to statistics_path(I18n.locale), method: :get, class: "item #{active_class('categories', 'index')}"
      i.browser.icon
      = t 'slayout.sheader.stat'


    .ui.right.menu.text
      .item style='height: 10px !important;margin: -23px 0 0;'
        = search_form_for @q do |f|
          = f.text_field :title_cont, :type => 'search', :class => 'search-input', placeholder: "Search", autocomplete: "off"
          /= f.submit

      - if user_signed_in?

        = link_to new_campaign_path(I18n.locale), method: :get, class: "item #{active_class('campaigns', 'new')}"
          i.upload.basic.icon
          = t 'slayout.sheader.newCamp'

        = link_to dashboard_path(I18n.locale), method: :get, class: "item #{active_class('users', 'show')}"
          i.thumbs.user.icon
          small
            = t 'slayout.header.welcome'
            = " #{current_user.name}"

        = link_to destroy_user_session_path(I18n.locale,), method: :delete, class: "ui pop-up item #{active_class('devise/sessions', 'destroy')}", 'data-content' => "Sign Out. <i class='icon meh' /> <br/> We 'll miss u!", 'data-position'=>"bottom left", style: 'margin:0;'
          i.sign.out.icon

      - else
        = link_to new_user_registration_path(I18n.locale), class: "item #{active_class('devise/registrations', 'new')}"
          = t 'slayout.sheader.signup'
          i.sign.in.icon
        = link_to new_user_session_path(I18n.locale), class: "item #{active_class('devise/sessions', 'new')}"
          = t 'slayout.sheader.signin'
          i.user.icon

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "BucksBacker"
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    / = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/highcharts/2.3.5/highcharts.js", "chartkick"
    / = stylesheet_link_tag 'jquery.rambling.slider'
    / = javascript_include_tag 'jquery.rambling.slider'
    = csrf_meta_tags
    - if content_for?(:meta)
      = yield(:meta)
    / link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Open+Sans:300italic,400,300,700' rel='stylesheet' type='text/css'
    /link href='http://fonts.googleapis.com/css?family=Montserrat:300' rel='stylesheet' type='text/css'

  body
    = render 'layouts/header'
      / .ui.segment.main_container.basic
      /   .column
      /     .container style="padding:20px 30px 0;"


    - if @root == true
      / #wrapper style='height:575px; width: 1140px; margin: 10px auto;'
      /   .slider-wrapper.theme-default
      /     .ribbon
      /     #slider.ramblingSlider style='width:100%;  margin:0px auto 0 auto;'

      .banner-wrapper
        = semantic_flash
        .banner
          ul
            li.one
              h1 Preserving hearts
              p the red ones*
              /a class="btn" href="#download"
                /| Download
            li.two
              h1 Educating India
              p Q1: spot the teacher
              /a class="btn" href="#download"
                /| Download
            li.three
              h1 Help the needy
              p You got too much in ur pockets.
              /a class="btn" href="#download"
                /| Download
            li.four
              h1 The last ultimatum
              p Next ultimatum - Coming Soon!
              /a class="btn" href="#download"
                /| Download
            li.five
              h1 Ok. Guys Money.
              p which you'll be donating soon!
              /a class="btn" href="#download"
                /| Download
            li.six
              h1 Protecting mother earth
              p Specially the flying fish*
              /a class="btn" href="#download"
                /| Download
            li.seven
              h1 Hope is a good thing
              p No comments
              /a class="btn" href="#download"
                /| Download
            li.eight
              h1 Helping hands
              p Lets make it big - hand by hand
              /a class="btn" href="#download"
                /| Download

    .ui.basic.segment.no_margin.body_container
      = semantic_flash unless @root == true

      /.ui.segment.basic.full.width.no_radius.no_pad.main_container
      = yield

    = render 'layouts/footer'